#Main configuration file for spring boot
server:
  port: 8080
  tomcat:
    max-connections: 1000
    max-threads: 200
    redirect-context-root: true
spring:
  application:
    name: OperationEngine
  http:
    converters:
      preferred-json-mapper: jackson
    encoding:
      charset: UTF-8
      enabled: true
  jackson:
    mapper:
      SORT_PROPERTIES_ALPHABETICALLY: true
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      ORDER_MAP_ENTRIES_BY_KEYS: true
  resources:
    static-locations:
      - classpath:/web/