#Main configuration file for spring boot
server:
  port: 8080
  tomcat:
    max-connections: 1000
    max-threads: 200
    redirect-context-root: true
spring:
  application:
    name: OperationEngine
  http:
    converters:
      preferred-json-mapper: jackson
    encoding:
      charset: UTF-8
      enabled: true
  jackson:
    mapper:
      SORT_PROPERTIES_ALPHABETICALLY: true
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      ORDER_MAP_ENTRIES_BY_KEYS: true
      WRITE_DATE_KEYS_AS_TIMESTAMPS: true
      WRITE_DATES_AS_TIMESTAMPS: true
      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
  main:
    banner-mode: off
  rabbitmq:
    listener:
      direct:
        acknowledge-mode: manual
        prefetch: 1
      simple:
        acknowledge-mode: manual
        prefetch: 1
  resources:
    static-locations:
      - classpath:/META-INF/resources/
      - classpath:/public/
      - classpath:/resources/
      - classpath:/static/
      - classpath:/web/