#Multi-threading and load management configuration
sixsense:
  threads:
    engine:
      allowed-idle-time: 60s
      maximum-threads: 2147483647
      minimum-threads: 0
      threadNamePrefix: "engine-worker-"
    http:
      allowed-idle-time: 30s
      maximum-threads: 2147483647
      minimum-threads: 10
      threadNamePrefix: "engine-http-listener-"
    amqp:
      allowed-idle-time: 30s
      maximum-threads: 2147483647
      minimum-threads: 10
      threadNamePrefix: "engine-amqp-consumer-"
